### ISSUE TITLE
request body must be a json raw

### ISSUE THREAD

**Issue by TrapDrap** [emrovsky/roblox-account-generator#5]
I've tinkered around with the source for a few hours now, I keep getting this error
`request body must be a json raw` when it tries to solve the captcha
I tried sending my own requests without the library to capsolver, and it matches up to their documentation, but it would not return me other than `{"errorCode":"ERROR_INVALID_TASK_DATA","errorDescription":"request body must be a json raw","errorId":1}`

**Comment by realsentence** [comment]
> I've tinkered around with the source for a few hours now, I keep getting this error `request body must be a json raw` when it tries to solve the captcha I tried sending my own requests without the library to capsolver, and it matches up to their documentation, but it would not return me other than `{"errorCode":"ERROR_INVALID_TASK_DATA","errorDescription":"request body must be a json raw","errorId":1}`

POST https://api.capsolver.com/createTask
Host: api.capsolver.com
Content-Type: application/json

{
    "clientKey": "YOUR_API_KEY_HERE",
    "task": {
        "type":"FunCaptchaTaskProxyLess", //Required
        "websiteURL":"", //Required
        "websitePublicKey":"", //Required
        "data": "{\"blob\": \"flaR60YY3tnRXv6w.l32U2KgdgEUCbyoSPI4jOxU...\"}" // Optional
    }
}

**Comment by emrovsky** [comment]
must be solved
